alias: "NB: WHIRLPOOL: Chill to Whirlpool Temp (V1.1 - KEPLER-107c)"
description: Chill wort from boil temp to whirlpool temp (~80°C) using HXG
triggers:
  - entity_id: input_boolean.prc_chill_to_whirlpool_temp
    to: "on"
    id: start
    trigger: state
  - entity_id: input_boolean.prc_chill_to_whirlpool_temp
    to: "off"
    id: stop
    trigger: state
  - entity_id: input_boolean.emergency
    to: "on"
    id: emergency
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: start
        sequence:
          - action: system_log.write
            data:
              message: "CHILL TO WHIRLPOOL: Start sequence initiated"
              level: warning
          - action: pyscript.execute_process
            data:
              process_name: p020
          - action: system_log.write
            data:
              message: "CHILL TO WHIRLPOOL: Valves configured (p020), waiting 3s"
              level: warning
          - delay:
              seconds: 3
          - action: input_number.set_value
            target:
              entity_id: input_number.prc_wort_pump_speed
            data:
              value: 5000
          - action: input_number.set_value
            target:
              entity_id: input_number.clt_speed
            data:
              value: 1550
          - action: system_log.write
            data:
              message: "CHILL TO WHIRLPOOL: Pump speeds set (Wort: 5000, CLT: 1550)"
              level: warning
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.clt_pump
          - action: system_log.write
            data:
              message: "CHILL TO WHIRLPOOL: CLT pump started, waiting 3s"
              level: warning
          - delay:
              seconds: 3
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.prc_wort_pump
          - action: system_log.write
            data:
              message: "CHILL TO WHIRLPOOL: Both pumps running (manual stop required)"
              level: warning
      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - action: system_log.write
            data:
              message: "CHILL TO WHIRLPOOL: Manual stop triggered"
              level: warning
          - action: script.nb_0000_god_mode_system_shutdown_safe_reset
          - action: system_log.write
            data:
              message: "CHILL TO WHIRLPOOL: Shutdown complete"
              level: warning
      - conditions:
          - condition: trigger
            id: emergency
        sequence:
          - action: system_log.write
            data:
              message: "🚨 CHILL TO WHIRLPOOL: EMERGENCY STOP - Calling GOD MODE"
              level: error
          - action: script.nb_0000_god_mode_system_shutdown_safe_reset
mode: restart
