alias: "NB: WHIRLPOOL: Whirlpool (V1.1 - KEPLER-107c)"
description: Whirlpool process to create vortex and settle trub in kettle center
triggers:
  - entity_id: input_boolean.prc_whirlpool
    to: "on"
    id: start
    trigger: state
  - entity_id: input_boolean.prc_whirlpool
    to: "off"
    id: stop
    trigger: state
  - entity_id: input_boolean.emergency
    to: "on"
    id: emergency
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: start
        sequence:
          - action: system_log.write
            data:
              message: "WHIRLPOOL: Start sequence initiated"
              level: warning
          - action: pyscript.execute_process
            data:
              process_name: p021
          - action: system_log.write
            data:
              message: "WHIRLPOOL: Valves configured (p021), waiting 3s"
              level: warning
          - delay:
              seconds: 3
          - action: input_number.set_value
            target:
              entity_id: input_number.prc_wort_pump_speed
            data:
              value: 3000
          - action: system_log.write
            data:
              message: "WHIRLPOOL: Wort pump speed set to 3000 RPM"
              level: warning
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.clt_pump
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.prc_wort_pump
          - action: system_log.write
            data:
              message: "WHIRLPOOL: Wort pump running at 3000 RPM (CLT pump OFF)"
              level: warning
      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - action: system_log.write
            data:
              message: "WHIRLPOOL: Manual stop triggered"
              level: warning
          - action: script.nb_0000_god_mode_system_shutdown_safe_reset
          - action: system_log.write
            data:
              message: "WHIRLPOOL: Shutdown complete - Boolean OFF (settling externally)"
              level: warning
      - conditions:
          - condition: trigger
            id: emergency
        sequence:
          - action: system_log.write
            data:
              message: "🚨 WHIRLPOOL: EMERGENCY STOP - Calling GOD MODE"
              level: error
          - action: script.nb_0000_god_mode_system_shutdown_safe_reset
mode: restart
